// components/NavBar.vue
<template>
  <div>
    <div
      class="flex justify-center items-center gap-2 p-4"
      :class="{ 'flex-col': vertical }"
    >
      <NuxtLink
        v-if="vertical"
        to="/"
        class="border-2 border-solid border-transparent hover:border-gray-300 rounded-2xl"
      >
        <div
          class="p-1 transition-all duration-300 flex justify-center items-center"
          :style="{
            width: '64px',
            height: '64px',
          }"
        >
          <div
            class="w-full h-full bg-gray-100 rounded-lg flex justify-center items-center"
          >
            <UIcon name="i-lucide-house" class="size-[32px]" />
          </div>
        </div>
      </NuxtLink>
      <NuxtLink
        v-for="game in games"
        :key="game.key"
        :to="`/announcement/${game.key}`"
        class="border-2 border-solid border-transparent hover:border-gray-300 rounded-2xl"
      >
        <div class="p-1 transition-all duration-300">
          <img
            :src="game.icon"
            :alt="game.name"
            :title="game.name"
            class="games-icon rounded-lg w-[64px] transition-all duration-300"
            :style="{
              'view-transition-name': `games-icon-${game.key}`,
            }"
            :class="{ 'sm:w-[128px]': !vertical }"
          />
        </div>
      </NuxtLink>
    </div>
  </div>
</template>

<script setup lang="ts">
import { games } from "~/constants/game";

withDefaults(
  defineProps<{
    vertical?: boolean;
  }>(),
  {
    vertical: false,
  }
);
</script>

<style scoped>
.router-link-active {
  border-color: #3778e5;
}
</style>

// src/components/nav-bar.tsx
import { Link } from "@tanstack/react-router";
import { House } from "lucide-react";
import { cn } from "#/lib/utils";
import { games } from "#/utils/games";
import { gameIconProcess } from "#/utils/image-processing";

export function NavBar({ vertical = false }: { vertical?: boolean }) {
  return (
    <nav className={cn("flex items-center justify-center gap-2 p-4", vertical && "flex-col")}>
      {vertical && (
        <Link
          to="/"
          preload="intent"
          aria-label="首页"
          className="rounded-icon border-2 border-solid border-transparent hover:border-gray-300"
          activeOptions={{ exact: true }}
          activeProps={{ className: "game-link-active" }}
        >
          <div className="flex items-center justify-center p-1 transition-all duration-300">
            <div className="rounded-icon flex size-16 items-center justify-center bg-gray-100 dark:bg-gray-700">
              <House className="size-10" />
            </div>
          </div>
        </Link>
      )}
      {games.map((game, index) => (
        <Link
          key={game.key}
          to="/announcement/$game"
          params={{ game: game.key }}
          preload="intent"
          aria-label={game.name}
          className="rounded-icon border-2 border-solid border-transparent hover:border-gray-300"
          activeOptions={{ exact: true }}
          activeProps={{ className: "game-link-active" }}
          style={{ viewTransitionName: `games-icon-${game.key}` }}
        >
          <div className="p-1 transition-all duration-300">
            <img
              src={gameIconProcess(game.icon)}
              alt={game.name}
              title={game.name}
              width={vertical ? 128 : 64}
              height={vertical ? 128 : 64}
              fetchPriority={!vertical && index === 0 ? "high" : "auto"}
              className={cn("rounded-icon w-16 transition-all duration-300", !vertical && "sm:w-32")}
            />
          </div>
        </Link>
      ))}
    </nav>
  );
}
